---
- name: restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted

- name: enable nginx systemd
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
