---
- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: prometheus systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: prometheus

- name: node-exporter systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: prometheus-node-exporter.service