---
- name: start grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: started

- name: restart grafana
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted

- name: enable grafana
  ansible.builtin.systemd:
    daemon_reload: yes
    name: grafana-server
    enabled: yes
    state: started

- name: node-exporter systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: prometheus-node-exporter.service